book_store2/config/routes.rb
Rails.application.routes.draw do
  get '/users/:id', to: 'users#index'
  resources :dashboard

  match '/users/:id',     to: 'users#show',       via: 'get'
  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]
  
  root 'welcome#index'
  resources :books
  resources :books do
  resources :comments
  end
end

book_store2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

book_store2/app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :author, presence: true
    belongs_to :user
    has_many :comments
end

book_store2/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  scope :approved, -> {where(accept: true)}
end

book_store2/app/models/user.rb
class User < ApplicationRecord
  attr_writer :login
  before_create :set_username
    # validates_length_of :username,
    # :within => 5..50,
    # :too_short => 'too short username, min 5 characters',
    # :too_long => 'too long username, max 50 characters',
    # :presence => true
  validate :validate_username
  has_many :books
  has_many :comments, through: :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  def login
    @login || self.username || self.email
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
  private
    def set_username
      self.username = self.email.split("@").first
    end  
end

book_store2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
      added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

book_store2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /books
  # GET /books.json
  def index
    @books = current_user.books

  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_index_path, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :pagecount, :status)
    end
end

book_store2/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
    def create
        @book = Book.find(params[:book_id])
        @comment = @book.comments.create(comment_params)
        redirect_to book_path(@book)
    end
    def edit
      @comment = Comment.find(params[:id])   
      @book = Book.find(params[:book_id])
    end
    def update
      @comment = Comment.find(params[:id]) 
      if @comment.update_attributes(:accept => true)
        redirect_to dashboard_index_url
      else
        render 'edit'
      end
    end
     
      private
        def comment_params
          params.require(:comment).merge(user_id: current_user.id).permit(:title, :content, :user_id)      
        
        end
end

book_store2/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @books = current_user.books.includes(:comments)
  end
end

book_store2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user = User.find_by_id(params[:id])
    @books = Book.where(status: true,user_id: @user) 
  end
end

book_store2/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user.present?
      redirect_to dashboard_index_path
    else
      @books = Book.where(status: true)
    end
  end
end

book_store2/app/helpers/application_helper.rb
module ApplicationHelper
end

book_store2/app/helpers/books_helper.rb
module BooksHelper
end

book_store2/app/helpers/comments_helper.rb
module CommentsHelper
end

book_store2/app/helpers/dashboard_helper.rb
module DashboardHelper
end

book_store2/app/helpers/users_helper.rb
module UsersHelper
end

book_store2/app/helpers/welcome_helper.rb
module WelcomeHelper
end

book_store2/app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :pagecount %>
    <%= form.number_field :pagecount %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

book_store2/app/views/books/comment.html.erb
<h1>merhaba<h1>

book_store2/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', dashboard_index_path %>

book_store2/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Pagecount</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.pagecount %></td>
        <td><%= book.status %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>
<%= link_to 'Back', root_path%>

book_store2/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', dashboard_index_path %>

book_store2/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Pagecount:</strong>
  <%= @book.pagecount %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p> 

<h2>Comments</h2>
<% @book.comments.approved.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.title %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.content %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_with(model: [ @book, @book.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <% end %>
<%= link_to 'Back', dashboard_index_path %>

book_store2/app/views/comments/_comments.html.erb
<% @book.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.title %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.content %>
  </p>

book_store2/app/views/comments/_form.html.erb
<%= form_with(model: [ @book, @book.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <% end %>

book_store2/app/views/comments/edit.html.erb
<p>
  <strong>Book Information :</strong>
  <%= @comment.book.title %>
</p>

<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>
 
<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= form_for([@book, @comment]) do |list| %>
  <%= list.submit "Approve" %>
<% end %>

book_store2/app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

  
    <% @books.each do |book| %>
      <% book.comments.each do |comment| %>
      <%= comment.title %> 
      <%= comment.content %>
     <p> 
       <%= comment.user.username %> commented on your <%= comment.book.title %> book. <i><%= link_to 'Click here', edit_book_comment_path(book, comment) %></i> to accept it.
    </p>
    <% end %>
    <%end%>
    
  
  
<br>

<%= link_to 'New Book', new_book_path %>

book_store2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.username %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
    <%= yield %>
  </body>
</html>

book_store2/app/views/users/index.html.erb
<%if user_signed_in?%>
  
    <%= @user.username %><br/>
    <%= @user.email %><br/>
  
    <% if @user.books.any?%>
      <table>
     <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Pagecount</th>
      </tr>
      
      </thead>

     <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.pagecount %></td>
          <td><%= link_to 'Show', book %></td>        </tr>
      <% end %>
      
      </tbody>
      </table>
      
    <%else%>
    <%end%>   
    
<%else%>
  <p><strong>If you want to see users profile you have to sign in</strong></p>
<% end %>

book_store2/app/views/welcome/index.html.erb
<h1>Welcome The Book Store</h1>
<p><i>Everything is working with by barter</i></p>
<p><i>If you wanna share or take book you need to register or login</i></p>
    
    <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Pagecount</th>
      <th>User Name</th>
    </tr>
    
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.pagecount %></td>
        <td><%= book.user.username %></td>
      </tr>
    <% end %>
  </tbody>
    </table>
    